org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# Let the app's own android.defaultConfig.ndk.abiFilters decide which ABIs to
# build instead of Flutter's default list. Required because Chaquopy only ships
# CPython for 64-bit ABIs.
disable-abi-filtering=true
